'use strict';

export const card = [ 
    'back',
    'spade-ace', 'spade-1', 'spade-2', 'spade-3', 'spade-4', 'spade-5', 'spade-6', 'spade-7', 'spade-8', 'spade-9', 'spade-10', 'spade-J', 'spade-jack', 'spade-C', 'spade-knight', 'spade-Q', 'spade-queen', 'spade-K', 'spade-king',
    'heart-ace', 'heart-1', 'heart-2', 'heart-3', 'heart-4', 'heart-5', 'heart-6', 'heart-7', 'heart-8', 'heart-9', 'heart-10', 'heart-J', 'heart-jack', 'heart-C', 'heart-knight', 'heart-Q', 'heart-queen', 'heart-K', 'heart-king',
    'diamond-ace', 'diamond-1', 'diamond-2', 'diamond-3', 'diamond-4', 'diamond-5', 'diamond-6', 'diamond-7', 'diamond-8', 'diamond-9', 'diamond-10', 'diamond-J', 'diamond-jack', 'diamond-C', 'diamond-knight', 'diamond-Q', 'diamond-queen', 'diamond-K', 'diamond-king',
    'club-ace', 'club-1', 'club-2', 'club-3', 'club-4', 'club-5', 'club-6', 'club-7', 'club-8', 'club-9', 'club-10', 'club-J', 'club-jack', 'club-C', 'club-knight', 'club-Q', 'club-queen', 'club-K', 'club-king',
    'joker-red', 'joker-black', 'joker-white',
    'trump-fool', 'trump-1', 'trump-2', 'trump-3', 'trump-4', 'trump-5', 'trump-6', 'trump-7', 'trump-8', 'trump-9', 'trump-10', 'trump-11', 'trump-12', 'trump-13', 'trump-14', 'trump-15', 'trump-16', 'trump-17', 'trump-18', 'trump-19', 'trump-20', 'trump-21', 
];
export const chess = [
    'white-king', 'white-queen', 'white-rook', 'white-bishop', 'white-knight', 'white-pawn', 
    'black-king', 'black-queen', 'black-rook', 'black-bishop', 'black-knight', 'black-pawn', 
];
export const domino = [
    'horizontal-back', 
    'horizontal-0-0', 'horizontal-0-1', 'horizontal-0-2', 'horizontal-0-3', 'horizontal-0-4', 'horizontal-0-5', 'horizontal-0-6', 
    'horizontal-1-0', 'horizontal-1-1', 'horizontal-1-2', 'horizontal-1-3', 'horizontal-1-4', 'horizontal-1-5', 'horizontal-1-6', 
    'horizontal-2-0', 'horizontal-2-1', 'horizontal-2-2', 'horizontal-2-3', 'horizontal-2-4', 'horizontal-2-5', 'horizontal-2-6', 
    'horizontal-3-0', 'horizontal-3-1', 'horizontal-3-2', 'horizontal-3-3', 'horizontal-3-4', 'horizontal-3-5', 'horizontal-3-6', 
    'horizontal-4-0', 'horizontal-4-1', 'horizontal-4-2', 'horizontal-4-3', 'horizontal-4-4', 'horizontal-4-5', 'horizontal-4-6', 
    'horizontal-5-0', 'horizontal-5-1', 'horizontal-5-2', 'horizontal-5-3', 'horizontal-5-4', 'horizontal-5-5', 'horizontal-5-6', 
    'horizontal-6-0', 'horizontal-6-1', 'horizontal-6-2', 'horizontal-6-3', 'horizontal-6-4', 'horizontal-6-5', 'horizontal-6-6', 

    'vertical-back', 
    'vertical-0-0', 'vertical-0-1', 'vertical-0-2', 'vertical-0-3', 'vertical-0-4', 'vertical-0-5', 'vertical-0-6', 
    'vertical-1-0', 'vertical-1-1', 'vertical-1-2', 'vertical-1-3', 'vertical-1-4', 'vertical-1-5', 'vertical-1-6', 
    'vertical-2-0', 'vertical-2-1', 'vertical-2-2', 'vertical-2-3', 'vertical-2-4', 'vertical-2-5', 'vertical-2-6', 
    'vertical-3-0', 'vertical-3-1', 'vertical-3-2', 'vertical-3-3', 'vertical-3-4', 'vertical-3-5', 'vertical-3-6', 
    'vertical-4-0', 'vertical-4-1', 'vertical-4-2', 'vertical-4-3', 'vertical-4-4', 'vertical-4-5', 'vertical-4-6', 
    'vertical-5-0', 'vertical-5-1', 'vertical-5-2', 'vertical-5-3', 'vertical-5-4', 'vertical-5-5', 'vertical-5-6', 
    'vertical-6-0', 'vertical-6-1', 'vertical-6-2', 'vertical-6-3', 'vertical-6-4', 'vertical-6-5', 'vertical-6-6', 
];

export const emoji = [
    'face', 'face-smile', 'face-smile-tears', 
    'face-mouth', 'face-mouth-smile', 'face-mouth-smile-sweat', 'face-mouth-close',
    'face-angel', 'face-demon', 'face-wink', 'face-smiling', 'face-delicious', 
    'face-relieved', 'face-heart', 'face-sunglass', 'face-smirking', 'face-neutral', 
    'face-expressionless', 'face-unamused', 'face-sweat', 'face-pensive', 'face-confused', 
    'face-confounded', 'face-kiss', 'face-kiss-heart', 'face-kiss-smile', 'face-kiss-close', 
    'face-tongue', 'face-tongue-wink', 'face-tongue-close', 'face-disappointed', 'face-worry', 
    'face-angry', 'face-pounting', 'face-cry', 'face-persever', 'face-triumph', 
    'face-disappointed-relieved', 'face-mouth-frowning', 'face-anguished', 'face-fearful', 
    'face-weary', 'face-sleepy', 'face-tired', 'face-grimacing', 'face-cry-loudly', 
    'face-surprised', 'face-hushed', 'face-surprised-sweat', 'face-screaming', 'face-astonished', 
    'face-flushed', 'face-sleeping', 'face-dizzy', 'face-quiet', 'face-medical', 
    'cat-smile-grinning', 'cat-smile-tears', 'cat-mouth', 'cat-heart', 'cat-wry', 
    'cat-kiss-smile', 'cat-pouting', 'cat-crying', 'cat-weary',
    'face-frowning-slight', 'face-smile-tight', 'face-upside-down', 'face-rolling-eyes', 
    'face-gesture-no', 'face-gesture-ok', 'face-gesture-bowing', 
    'monkey-see-no-evil', 'monkey-hear-no-evil', 'monkey-speak-no-evil', 
    'face-gesture-hey', 'face-gesture-frowning', 'hand-celebrate', 
    'face-gesture-pouting', 'hand-please', 
];

export const fontawesome = [ 
    '500px', 'address-book', 'address-book-o', 'address-card', 'address-card-o', 'adjust', 
    'adn', 'align-center', 'align-justify', 'align-left', 'align-right', 'amazon', 'ambulance', 
    'american-sign', 'anchor', 'android', 'angellist', 'angle-double-down', 'angle-double-left', 
    'angle-double-right', 'angle-double-up', 'angle-down', 'angle-left', 'angle-right', 'angle-up', 
    'apple', 'archive', 'area-chart', 'arrow-circle-down', 'arrow-circle-left', 'arrow-circle', 
    'arrow-circle', 'arrow-circle', 'arrow-circle', 'arrow-circle-right', 'arrow-circle-up', 
    'arrow-down', 'arrow-left', 'arrow-right', 'arrow-up', 'arrows', 'arrows-alt', 'arrows-h', 
    'arrows-v', 'asl-interpreting', 'assistive-listening-systems', 'asterisk', 'at', 'audio-description', 
    'automobile', 'backward', 'balance-scale', 'ban', 'bandcamp', 'bank', 'bar-chart', 'bar-chart-o', 
    'barcode', 'bars', 'bath', 'bathtub', 'battery', 'battery-0', 'battery-1', 'battery-2', 'battery-3', 
    'battery-4', 'battery-empty', 'battery-full', 'battery-half', 'battery-quarter', 'battery-three-quarters', 
    'bed', 'beer', 'behance', 'behance-square', 'bell', 'bell-o', 'bell-slash', 'bell-slash-o', 'bicycle', 
    'binoculars', 'birthday-cake', 'bitbucket', 'bitbucket-square', 'bitcoin', 'black-tie', 'blind', 'bluetooth', 
    'bluetooth-b', 'bold', 'bolt', 'bomb', 'book', 'bookmark', 'bookmark-o', 'braille', 'briefcase', 'btc', 'bug', 
    'building', 'building-o', 'bullhorn', 'bullseye', 'bus', 'buysellads', 'cab', 'calculator', 'calendar', 
    'calendar-check-o', 'calendar-minus-o', 'calendar-o', 'calendar-plus-o', 'calendar-times-o', 'camera', 
    'camera-retro', 'car', 'caret-down', 'caret-left', 'caret-right', 'caret-square', 'caret-square', 
    'caret-square', 'caret-square', 'caret-up', 'cart-arrow-down', 'cart-plus', 'cc', 'cc-amex', 
    'cc-diners-club', 'cc-discover', 'cc-jcb', 'cc-mastercard', 'cc-paypal', 'cc-stripe', 'cc-visa', 
    'certificate', 'chain', 'chain-broken', 'check', 'check-circle', 'check-circle-o', 'check-square', 
    'check-square-o', 'chevron-circle-down', 'chevron-circle-left', 'chevron-circle-right', 'chevron-circle-up', 
    'chevron-down', 'chevron-left', 'chevron-right', 'chevron-up', 'child', 'chrome', 'circle', 'circle-o', 
    'circle-o-notch', 'circle-thin', 'clipboard', 'clock-o', 'clone', 'close', 'cloud', 'cloud-download', 
    'cloud-upload', 'cny', 'code', 'code-fork', 'codepen', 'codiepie', 'coffee', 'cog', 'cogs', 'columns', 
    'comment', 'comment-o', 'commenting', 'commenting-o', 'comments', 'comments-o', 'compass', 'compress', 
    'connectdevelop', 'contao', 'copy', 'copyright', 'creative-commons', 'credit-card', 'credit-card-alt', 
    'crop', 'crosshairs', 'css3', 'cube', 'cubes', 'cut', 'cutlery', 'dashboard', 'dashcube', 'database', 
    'deaf', 'deafness', 'dedent', 'delicious', 'desktop', 'deviantart', 'diamond', 'digg', 'dollar', 
    'dot-circle-o', 'download', 'dribbble', 'drivers-license', 'drivers-license-o', 'dropbox', 'drupal', 
    'edge', 'edit', 'eercast', 'eject', 'ellipsis-h', 'ellipsis-v', 'empire', 'envelope', 'envelope-o', 
    'envelope-open', 'envelope-open-o', 'envelope-square', 'envira', 'eraser', 'etsy', 'eur', 'euro', 
    'exchange', 'exclamation', 'exclamation-circle', 'exclamation-triangle', 'expand', 'expeditedssl', 
    'external-link', 'external-link-square', 'eye', 'eye-slash', 'eyedropper', 'fa', 'facebook', 
    'facebook-f', 'facebook-official', 'facebook-square', 'fast-backward', 'fast-forward', 'fax', 
    'feed', 'female', 'fighter-jet', 'file', 'file-archive-o', 'file-audio-o', 'file-code-o', 
    'file-excel-o', 'file-image-o', 'file-movie-o', 'file-o', 'file-pdf-o', 'file-photo-o', 
    'file-picture-o', 'file-powerpoint-o', 'file-sound-o', 'file-text', 'file-text-o', 'file-video-o', 
    'file-word-o', 'file-zip-o', 'files-o', 'film', 'filter', 'fire', 'fire-extinguisher', 'firefox', 
    'first-order', 'flag', 'flag-checkered', 'flag-o', 'flash', 'flask', 'flickr', 'floppy-o', 'folder', 
    'folder-o', 'folder-open', 'folder-open-o', 'font', 'font-awesome', 'fonticons', 'fort-awesome', 
    'forumbee', 'forward', 'foursquare', 'free-code-camp', 'frown-o', 'futbol-o', 'gamepad', 'gavel', 
    'gbp', 'ge', 'gear', 'gears', 'genderless', 'get-pocket', 'gg', 'gg-circle', 'gift', 'git', 'git-square', 
    'github', 'github-alt', 'github-square', 'gitlab', 'gittip', 'glass', 'glide', 'glide-g', 'globe', 'google', 
    'google-plus', 'google-plus-circle', 'google-plus-official', 'google-plus-square', 'google-wallet', 
    'graduation-cap', 'gratipay', 'grav', 'group', 'h-square', 'hacker-news', 'hand-grab-o', 'hand-lizard-o', 
    'hand-o-down', 'hand-o-left', 'hand-o-right', 'hand-o-up', 'hand-paper-o', 'hand-peace-o', 'hand-pointer-o', 
    'hand-rock-o', 'hand-scissors-o', 'hand-spock-o', 'hand-stop-o', 'handshake-o', 'hard-of-hearing', 'hashtag', 
    'hdd-o', 'header', 'headphones', 'heart', 'heart-o', 'heartbeat', 'history', 'home', 'hospital-o', 'hotel', 
    'hourglass', 'hourglass-1', 'hourglass-2', 'hourglass-3', 'hourglass-end', 'hourglass-half', 'hourglass-o', 
    'hourglass-start', 'houzz', 'html5', 'i-cursor', 'id-badge', 'id-card', 'id-card-o', 'ils', 'image', 'imdb', 
    'inbox', 'indent', 'industry', 'info', 'info-circle', 'inr', 'instagram', 'institution', 'internet-explorer', 
    'intersex', 'ioxhost', 'italic', 'joomla', 'jpy', 'jsfiddle', 'key', 'keyboard-o', 'krw', 'language', 'laptop', 
    'lastfm', 'lastfm-square', 'leaf', 'leanpub', 'legal', 'lemon-o', 'level-down', 'level-up', 'life-bouy', 
    'life-buoy', 'life-ring', 'life-saver', 'lightbulb-o', 'line-chart', 'link', 'linkedin', 'linkedin-square', 
    'linode', 'linux', 'list', 'list-alt', 'list-ol', 'list-ul', 'location-arrow', 'lock', 'long-arrow-down', 
    'long-arrow-left', 'long-arrow-right', 'long-arrow-up', 'low-vision', 'magic', 'magnet', 'mail-forward', 
    'mail-reply', 'mail-reply-all', 'male', 'map', 'map-marker', 'map-o', 'map-pin', 'map-signs', 'mars', 
    'mars-double', 'mars-stroke', 'mars-stroke-h', 'mars-stroke-v', 'maxcdn', 'meanpath', 'medium', 'medkit', 
    'meetup', 'meh-o', 'mercury', 'microchip', 'microphone', 'microphone-slash', 'minus', 'minus-circle', 
    'minus-square', 'minus-square-o', 'mixcloud', 'mobile', 'mobile-phone', 'modx', 'money', 'moon-o', 
    'mortar-board', 'motorcycle', 'mouse-pointer', 'music', 'navicon', 'neuter', 'newspaper-o', 'object-group',
    'object-ungroup', 'odnoklassniki', 'odnoklassniki-square', 'opencart', 'openid', 'opera', 'optin-monster', 
    'outdent', 'pagelines', 'paint-brush', 'paper-plane', 'paper-plane-o', 'paperclip', 'paragraph', 'paste', 
    'pause', 'pause-circle', 'pause-circle-o', 'paw', 'paypal', 'pencil', 'pencil-square', 'pencil-square-o', 
    'percent', 'phone', 'phone-square', 'photo', 'picture-o', 'pie-chart', 'pied-piper', 'pied-piper-alt', 
    'pied-piper-pp', 'pinterest', 'pinterest-p', 'pinterest-square', 'plane', 'play', 'play-circle', 'play-circle-o', 
    'plug', 'plus', 'plus-circle', 'plus-square', 'plus-square-o', 'podcast', 'power-off', 'print', 'product-hunt', 
    'puzzle-piece', 'qq', 'qrcode', 'question', 'question-circle', 'question-circle-o', 'quora', 'quote-left', 
    'quote-right', 'ra', 'random', 'ravelry', 'rebel', 'recycle', 'reddit', 'reddit-alien', 'reddit-square', 
    'refresh', 'registered', 'remove', 'renren', 'reorder', 'repeat', 'reply', 'reply-all', 'resistance', 
    'retweet', 'rmb', 'road', 'rocket', 'rotate-left', 'rotate-right', 'rouble', 'rss', 'rss-square', 'rub', 
    'ruble', 'rupee', 's15', 'safari', 'save', 'scissors', 'scribd', 'search', 'search-minus', 'search-plus', 
    'sellsy', 'send', 'send-o', 'server', 'share', 'share-alt', 'share-alt-square', 'share-square', 'share-square-o', 
    'shekel', 'sheqel', 'shield', 'ship', 'shirtsinbulk', 'shopping-bag', 'shopping-basket', 'shopping-cart', 'shower', 
    'sign-in', 'sign-language', 'sign-out', 'signal', 'signing', 'simplybuilt', 'sitemap', 'skyatlas', 'skype', 'slack', 
    'sliders', 'slideshare', 'smile-o', 'snapchat', 'snapchat-ghost', 'snapchat-square', 'snowflake-o', 'soccer-ball-o', 
    'sort', 'sort-alpha-asc', 'sort-alpha-desc', 'sort-amount-asc', 'sort-amount-desc', 'sort-asc', 'sort-desc', 'sort-down', 
    'sort-numeric-asc', 'sort-numeric-desc', 'sort-up', 'soundcloud', 'space-shuttle', 'spinner', 'spoon', 'spotify', 'square', 
    'square-o', 'stack-exchange', 'stack-overflow', 'star', 'star-half', 'star-half-empty', 'star-half-full', 'star-half-o', 
    'star-o', 'steam', 'steam-square', 'step-backward', 'step-forward', 'stethoscope', 'sticky-note', 'sticky-note-o', 'stop', 
    'stop-circle', 'stop-circle-o', 'street-view', 'strikethrough', 'stumbleupon', 'stumbleupon-circle', 'subscript', 'subway', 
    'suitcase', 'sun-o', 'superpowers', 'superscript', 'support', 'table', 'tablet', 'tachometer', 'tag', 'tags', 'tasks', 'taxi', 
    'telegram', 'television', 'tencent-weibo', 'terminal', 'text-height', 'text-width', 'th', 'th-large', 'th-list', 'themeisle', 
    'thermometer', 'thermometer-0', 'thermometer-1', 'thermometer-2', 'thermometer-3', 'thermometer-4', 'thermometer-empty', 
    'thermometer-full', 'thermometer-half', 'thermometer-quarter', 'thermometer-three-quarters', 'thumb-tack', 'thumbs-down', 
    'thumbs-o-down', 'thumbs-o-up', 'thumbs-up', 'ticket', 'times', 'times-circle', 'times-circle-o', 'times-rectangle', 
    'times-rectangle-o', 'tint', 'toggle-down', 'toggle-left', 'toggle-off', 'toggle-on', 'toggle-right', 'toggle-up', 
    'trademark', 'train', 'transgender', 'transgender-alt', 'trash', 'trash-o', 'tree', 'trello', 'tripadvisor', 'trophy', 
    'truck', 'try', 'tty', 'tumblr', 'tumblr-square', 'turkish-lira', 'tv', 'twitch', 'twitter', 'twitter-square', 'umbrella', 
    'underline', 'undo', 'universal-access', 'university', 'unlink', 'unlock', 'unlock-alt', 'unsorted', 'upload', 'usb', 'usd', 
    'user', 'user-circle', 'user-circle-o', 'user-md', 'user-o', 'user-plus', 'user-secret', 'user-times', 'users', 'vcard', 
    'vcard-o', 'venus', 'venus-double', 'venus-mars', 'viacoin', 'viadeo', 'viadeo-square', 'video-camera', 'vimeo', 'vimeo-square', 
    'vine', 'vk', 'volume-control-phone', 'volume-down', 'volume-off', 'volume-up', 'warning', 'wechat', 'weibo', 'weixin', 'whatsapp', 
    'wheelchair', 'wheelchair-alt', 'wifi', 'wikipedia-w', 'window-close', 'window-close-o', 'window-maximize', 'window-minimize', 
    'window-restore', 'windows', 'won', 'wordpress', 'wpbeginner', 'wpexplorer', 'wpforms', 'wrench', 'xing', 'xing-square', 
    'y-combinator', 'y-combinator-square', 'yahoo', 'yc', 'yc-square', 'yelp', 'yen', 'yoast', 'youtube', 'youtube-play', 'youtube-square' 
];

export const mahjong = [
    'wind-east', 'wind-south', 'wind-west', 'wind-north', 
    'dragon-red', 'dragon-green', 'dragon-white', 
    'character-1', 'character-2', 'character-3', 'character-4', 'character-5', 'character-6', 'character-7', 'character-8', 'character-9', 
    'bamboo-1', 'bamboo-2', 'bamboo-3', 'bamboo-4', 'bamboo-5', 'bamboo-6', 'bamboo-7', 'bamboo-8', 'bamboo-9', 
    'circle-1', 'circle-2', 'circle-3', 'circle-4', 'circle-5', 'circle-6', 'circle-7', 'circle-8', 'circle-9', 
    'plum', 'orchid', 'bamboo', 'chrysanthemum', 
    'spring', 'summer', 'autumn', 'winter', 'joker', 
    'back', 
];